// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: math.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	X              []float32              `protobuf:"fixed32,1,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y              []float32              `protobuf:"fixed32,2,rep,packed,name=y,proto3" json:"y,omitempty"`
	Z              []float32              `protobuf:"fixed32,3,rep,packed,name=z,proto3" json:"z,omitempty"`
	FieldX         []float32              `protobuf:"fixed32,4,rep,packed,name=field_x,json=fieldX,proto3" json:"field_x,omitempty"`
	FieldY         []float32              `protobuf:"fixed32,5,rep,packed,name=field_y,json=fieldY,proto3" json:"field_y,omitempty"`
	FieldZ         []float32              `protobuf:"fixed32,6,rep,packed,name=field_z,json=fieldZ,proto3" json:"field_z,omitempty"`
	FieldAmplitude []float32              `protobuf:"fixed32,7,rep,packed,name=field_amplitude,json=fieldAmplitude,proto3" json:"field_amplitude,omitempty"`
	FieldSigma     []float32              `protobuf:"fixed32,8,rep,packed,name=field_sigma,json=fieldSigma,proto3" json:"field_sigma,omitempty"`
	Mass           []float32              `protobuf:"fixed32,9,rep,packed,name=mass,proto3" json:"mass,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeRequest) GetX() []float32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ComputeRequest) GetY() []float32 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *ComputeRequest) GetZ() []float32 {
	if x != nil {
		return x.Z
	}
	return nil
}

func (x *ComputeRequest) GetFieldX() []float32 {
	if x != nil {
		return x.FieldX
	}
	return nil
}

func (x *ComputeRequest) GetFieldY() []float32 {
	if x != nil {
		return x.FieldY
	}
	return nil
}

func (x *ComputeRequest) GetFieldZ() []float32 {
	if x != nil {
		return x.FieldZ
	}
	return nil
}

func (x *ComputeRequest) GetFieldAmplitude() []float32 {
	if x != nil {
		return x.FieldAmplitude
	}
	return nil
}

func (x *ComputeRequest) GetFieldSigma() []float32 {
	if x != nil {
		return x.FieldSigma
	}
	return nil
}

func (x *ComputeRequest) GetMass() []float32 {
	if x != nil {
		return x.Mass
	}
	return nil
}

type ComputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ax            []float32              `protobuf:"fixed32,1,rep,packed,name=ax,proto3" json:"ax,omitempty"`
	Ay            []float32              `protobuf:"fixed32,2,rep,packed,name=ay,proto3" json:"ay,omitempty"`
	Az            []float32              `protobuf:"fixed32,3,rep,packed,name=az,proto3" json:"az,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeResponse) GetAx() []float32 {
	if x != nil {
		return x.Ax
	}
	return nil
}

func (x *ComputeResponse) GetAy() []float32 {
	if x != nil {
		return x.Ay
	}
	return nil
}

func (x *ComputeResponse) GetAz() []float32 {
	if x != nil {
		return x.Az
	}
	return nil
}

var File_math_proto protoreflect.FileDescriptor

const file_math_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"math.proto\x12\x04math\"\xe3\x01\n" +
	"\x0eComputeRequest\x12\f\n" +
	"\x01x\x18\x01 \x03(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x03(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x03(\x02R\x01z\x12\x17\n" +
	"\afield_x\x18\x04 \x03(\x02R\x06fieldX\x12\x17\n" +
	"\afield_y\x18\x05 \x03(\x02R\x06fieldY\x12\x17\n" +
	"\afield_z\x18\x06 \x03(\x02R\x06fieldZ\x12'\n" +
	"\x0ffield_amplitude\x18\a \x03(\x02R\x0efieldAmplitude\x12\x1f\n" +
	"\vfield_sigma\x18\b \x03(\x02R\n" +
	"fieldSigma\x12\x12\n" +
	"\x04mass\x18\t \x03(\x02R\x04mass\"A\n" +
	"\x0fComputeResponse\x12\x0e\n" +
	"\x02ax\x18\x01 \x03(\x02R\x02ax\x12\x0e\n" +
	"\x02ay\x18\x02 \x03(\x02R\x02ay\x12\x0e\n" +
	"\x02az\x18\x03 \x03(\x02R\x02az2N\n" +
	"\x06Oracle\x12D\n" +
	"\x15CalculateAcceleration\x12\x14.math.ComputeRequest\x1a\x15.math.ComputeResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_math_proto_rawDescOnce sync.Once
	file_math_proto_rawDescData []byte
)

func file_math_proto_rawDescGZIP() []byte {
	file_math_proto_rawDescOnce.Do(func() {
		file_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)))
	})
	return file_math_proto_rawDescData
}

var file_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_math_proto_goTypes = []any{
	(*ComputeRequest)(nil),  // 0: math.ComputeRequest
	(*ComputeResponse)(nil), // 1: math.ComputeResponse
}
var file_math_proto_depIdxs = []int32{
	0, // 0: math.Oracle.CalculateAcceleration:input_type -> math.ComputeRequest
	1, // 1: math.Oracle.CalculateAcceleration:output_type -> math.ComputeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_math_proto_init() }
func file_math_proto_init() {
	if File_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_math_proto_goTypes,
		DependencyIndexes: file_math_proto_depIdxs,
		MessageInfos:      file_math_proto_msgTypes,
	}.Build()
	File_math_proto = out.File
	file_math_proto_goTypes = nil
	file_math_proto_depIdxs = nil
}
